# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: Marthlab

# Short description (goes below the title; it will also be used in the RSS feed)
description: genomics software and analysis

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
#baseurl: /path/to/blog 

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://marthlab.github.com/

#### Under the Hood Stuff #####

# Continue compiling even if there are errors. Keep it true, unless troubleshooting.
auto: true

# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: README.markdown, package.json, node_modules
